### PR TITLE
Fixed _updateValue and added _checkEnabled method to paragraph command

### LINKED ISSUE #16: Fix _updateValue and add _checkEnabled()
Currently paragraph commmand's `_updateValue` method looks like this:
```js
_updateValue() {
	const block = this.editor.document.selection.getSelectedBlocks().next().value;

	if ( block ) {
		this.value = block.is( 'paragraph' );
	}
}
```
So when we move selection from block to element which is not a block - it stays enabled.

Second thing - `refreshState()` is never called and `_checkEnabled` method is not implemented.

### LINKED ISSUE #3298: Fix _updateValue and add _checkEnabled()
Currently paragraph commmand's `_updateValue` method looks like this:
```js
_updateValue() {
	const block = this.editor.document.selection.getSelectedBlocks().next().value;

	if ( block ) {
		this.value = block.is( 'paragraph' );
	}
}
```
So when we move selection from block to element which is not a block - it stays enabled.

Second thing - `refreshState()` is never called and `_checkEnabled` method is not implemented.

### PR DESCRIPTION
**Pull request by szymonkups**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Paragraph command correctly updates its value and isEnabled properties. Closes ckeditor/ckeditor5#3298.

### CODE REVIEW

File: src/paragraphcommand.js [hunk 1]
```diff
@@ -69,10 +72,28 @@ export default class ParagraphCommand extends Command {
...
+	 * @inheritDoc
+	 */
+	_checkEnabled() {
+		const block = this._getSelectedBlock();
+		const schema = this.editor.document.schema;
 
-		if ( block ) {
-			this.value = block.is( 'paragraph' );
-		}
+		return !!block && schema.check( { name: 'paragraph', inside: block.parent.name } ) && !schema.objects.has( block.name );
```
Comment (Reinmar) [inline src/paragraphcommand.js]: Use with position, like this:

```js
		const isMQAllowed = schema.check( {
			name: 'messageQuote',
			inside: Position.createBefore( firstBlock )
		} );
```

Then, the schema will have entire context to check, not only the name.

File: src/paragraphcommand.js [hunk 2]
```diff
@@ -69,10 +72,28 @@ export default class ParagraphCommand extends Command {
...
+	}
+
+	/**
+	 * Returns currently selected block.
+	 *
+	 * @private
+	 * @returns {module:engine/model/element~Element}
+	 */
+	_getSelectedBlock() {
+		return this.editor.document.selection.getSelectedBlocks().next().value;
```
Comment (Reinmar) [inline src/paragraphcommand.js]: Use `first()` from ckeditor5-utils. Also, I think you can repeat this code twice and avoid a method. Or make it a function. Let's not put too many things to prototypes – that makes classes unnecessarily harder to read. OFC, there's nothing particularly wrong in this, but I would do it differently to avoid the minimal bloat it brought.

File: tests/paragraphcommand.js [hunk 3]
```diff
@@ -61,6 +68,19 @@ describe( 'ParagraphCommand', () => {
 			setData( document, '<paragraph>[bar</paragraph><heading1>foo]</heading1>' );
 			expect( command.value ).to.be.true;
 		} );
+
+		it( 'has proper value when moved to element that is not a block', () => {
```
Comment (Reinmar) [inline tests/paragraphcommand.js]: You combined two tests here – that it reacts on changes and that it's off in a block. I'd propose splitting them to clarify what's the essential part of each of them because these are two completely separate behaviours.

File: src/paragraphcommand.js [hunk 4]
```diff
@@ -69,10 +72,28 @@ export default class ParagraphCommand extends Command {
 	 * @private
 	 */
 	_updateValue() {
```
Comment (Reinmar) [inline src/paragraphcommand.js]: In list command and block quote command this is a public method called `refreshValue()`. We can align paragraph command to them.

File: src/paragraphcommand.js [hunk 5]
```diff
@@ -69,10 +74,27 @@ export default class ParagraphCommand extends Command {
...
+			return false;
 		}
+
+		const schema = this.editor.document.schema;
+		const isParagraphAllowed = schema.check( {
+			name: 'paragraph',
+			inside: Position.createBefore( block )
+		} );
+
+		return isParagraphAllowed && !schema.objects.has( block.name );
```
Comment (Reinmar) [inline src/paragraphcommand.js]: I know we talked about this, but I'm not sure about the last bit. Why checking whether the block is an object too? That doesn't say yet that it cannot be turned into a paragraph. Or rather – it's an indication, just like being in `schema.limits` (which is even clearer indication). However, in the second case, the element won't be returned by `getSelectedBlocks()` because only blocks are returned by this method. So I think now that this is unnecessary here.

Besides, if you make this change here, we'd need to make it in all other similar commands. So I'd rather like to have it in one place – `getSelectedBlocks()`.
